export const ACQUIRE_PROJECTS_GET = "ACQUIRE_PROJECTS_GET";
export const REGISTER_PROJECT_POST = "REGISTER_PROJECT_POST";
export const CHANGE_PROJECT_PUT = "CHANGE_PROJECT_PUT";
export const REMOVE_PROJECT_DELETE = "REMOVE_PROJECT_DELETE";

export const ACQUIRE_TASKS_GET = "ACQUIRE_TASKS_GET";
export const REGISTER_TASK_POST = "REGISTER_TASK_POST";
export const CHANGE_TASK_PUT = "CHANGE_TASK_PUT";
export const REMOVE_TASK_DELETE = "REMOVE_TASK_DELETE";

export const ACQUIRE_TRACKERS_GET = "ACQUIRE_TRACKERS_GET";
export const REGISTER_TRACKER_POST = "REGISTER_TRACKER_POST";
export const CHANGE_TRACKERS_PUT = "CHANGE_TRACKER_PUT";
export const REMOVE_TRACKERS_DELETE = "REMOVE_TRACKER_DELETE";