export const ACQUIRE_PROJECTS_GET = "ACQUIRE_PROJECTS_GET";
export const REGISTER_PROJECTS_POST = "REGISTER_PROJECTS_POST";
export const CHANGE_PROJECT_PUT = "CHANGE_PROJECT_PUT";
export const REMOVE_PROJECT_DELETE = "REMOVE_PROJECT_DELETE";
