// TASK ITENS
export const INIT_TASK = "INIT_TASK"
export const ADD_TASK = "ADD_TASK"
export const EDIT_TASK = "EDIT_TASK"
export const DELETE_TASK = "DELETE_TASK"
// PROJECTS
export const INIT_PROJECTS = "INIT_PROJECTS"
export const ADD_PROJECTS = "ADD_PROJECTS"
export const EDIT_PROJECTS = "EDIT_PROJECTS"
export const DELETE_PROJECTS = "DELETE_PROJECTS"
// TIMER
export const INIT_WORK_DAY = "INIT_WORK_DAY"
export const FINISH_WORK_DAY = "FINISH_WORK_DAY"
export const CLEAN_ALL = "CLEAN_ALL"
// ALERTS
export const SHOW_ALERT = "SHOW_ALERT"
// TRACKERS
export const INIT_TRACKERS = "INIT_TRACKERS"
export const ADD_TRACKER = "ADD_TRACKER"
export const EDIT_TRACKER = "EDIT_TRACKER"
export const DELETE_TRACKER = "DELETE_TRACKER"