<template>
  <div class="alert">
    <article
      class="message"
      :class="getTypeAlert(index)"
      v-for="(alert, index) in getAlerts"
      :key="alert.id"
    >
      <div class="message-header">
        {{ alert.title }}
        <!-- <button class="delete" @click="close" aria-label="delete"></button> -->
      </div>
      <div class="message-body">
        {{ alert.text }}
      </div>
    </article>
  </div>
</template>

<script lang="ts">
import { AlertTypes } from "@/interfaces/IAlert";
import { defineComponent } from "vue";

export default defineComponent({
  name: "AlertMsg",
  computed: {
    getAlerts() {
      return this.$store.state.alerts;
    },
  },
  methods: {
    getTypeAlert(pos:number) {
      let tipo = this.$store.state.alerts[pos].alertType;
      switch (tipo) {
        case AlertTypes.SUCCESS:
          return "is-success slide-in-right slide-in-and-out-right";
        case AlertTypes.WARNING:
          return "is-warning slide-in-right slide-in-and-out-right";
        case AlertTypes.DANGER:
          return "is-danger slide-in-right slide-in-and-out-right";
      }
    },
  },
});
</script>


<style scoped>
.alert {
  position: absolute;
  bottom: 0;
  right: 0;
  margin-bottom: 10px;
  margin-right: 10px;
  width: 300px;
  z-index: 100;
}

.slide-in-and-out-right {
  -webkit-animation-delay: 0s, 3s ;
  -webkit-animation-duration: 0.5s, 0.8s;
  -webkit-animation-name: slide-in-right, slide-out-right;
  
  /* -webkit-animation: slide-in-right 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both, slide-in-right 0.9s cubic-bezier(0.550, 0.085, 0.680, 0.530) 3s both reverse; */
  animation-delay: 0s, 3s;
  animation-duration: 0.5s, 0.8s;
  animation-name: slide-in-right, slide-out-right;
  /* animation: slide-in-right 0.5s, slide-in-right 0.9s cubic-bezier(0.550, 0.085, 0.680, 0.530) 3s both reverse; */
}

/* .slide-out-right {
  -webkit-animation: slide-out-right 0.9s cubic-bezier(0.550, 0.085, 0.680, 0.530) 3s both;
  animation: slide-out-right 0.9s cubic-bezier(0.550, 0.085, 0.680, 0.530) 3s both;
} */

/* ----------------------------------------------
 * Generated by Animista on 2022-4-2 20:1:54
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-right
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2022-4-2 20:13:29
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-out-right
 * ----------------------------------------
 */
@-webkit-keyframes slide-out-right {
  0% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
}
@keyframes slide-out-right {
  0% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
}


</style>